name: Test

on: [push]

jobs:
  testfreebsd:
    runs-on: macos-latest
    name: A job to run test FreeBSD
    #env:
      #MYTOKEN : ${{ secrets.MYTOKEN }}
      #MYTOKEN2: "value2"
    steps:
    #- uses: actions/checkout@v2
    - name: Test in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.1.3
      with:
        #envs: 'MYTOKEN MYTOKEN2'
        prepare: |
          pkg install -y curl rsync git-lite bastille
          service sshd enable
          service sshd status
          sysrc bastille_enable=YES
          sysrc cloned_interfaces+=lo1
          sysrc ifconfig_lo1_name="bastille0"
          service netif cloneup
          echo 'ext_if="em0"' >> /etc/pf.conf
          echo 'set block-policy return' >> /etc/pf.conf
          echo 'set skip on lo' >> /etc/pf.conf
          echo 'set skip on bastille0' >> /etc/pf.conf
          echo 'table <jails> persist' >> /etc/pf.conf
          echo 'nat on $ext_if from <jails> to any -> ($ext_if:0)' >> /etc/pf.conf
          echo 'rdr-anchor "rdr/*"' >> /etc/pf.conf
          echo 'block in all' >> /etc/pf.conf
          echo 'pass out quick keep state' >> /etc/pf.conf
          echo 'pass in inet proto tcp from any to any port ssh flags any keep state' >> /etc/pf.conf
          service pf enable
          service pf start
          bastille bootstrap 12.2-RELEASE
          bastille create rsync_test 12.2-RELEASE bastille0 127.0.0.2
        usesh: true
        sync: sshfs
        run: |
          sockstat -4
          bastille bootstrap https://github.com/thenuh/bastille-templates-rsync
          bastille template rsync_test thenuh/bastille-templates-rsyncbastille\
          --arg ssh_username=asdf\
          --arg ssh_from_ip=0.0.0.0\
          --arg ssh_port=12222\
          --arg ssh_pwd=asdf1234\
          --arg ssh_key=sillypeas
